# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FBProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gs_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('fb_profile_link', models.URLField(null=True)),
                ('fb_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField(default=None, null=True)),
                ('end_time', models.TimeField(null=True)),
                ('venue', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('cover_link', models.URLField(null=True)),
                ('place_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GSProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gs_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('profile_pic', models.TextField(null=True)),
                ('subcategory', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255, null=True)),
                ('tag', models.TextField(null=True)),
                ('popular', models.TextField(null=True)),
                ('entity_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='involved_parties',
            field=models.ManyToManyField(to='web.GSProfile'),
        ),
    ]
